### ISSUE TITLE
Mistakes/typos in the documentation of PyInform

### ISSUE THREAD

**Issue by gvalentini85** [ELIFE-ASU/PyInform#27]
Documentation of relative entropy:
• b (double) – the base of the time series
• b – the logarithmic base

Should instead be:
• b – the base of the time series
• base (double) – the logarithmic base

Documentation of relative entropy:
- There is a "a the" instead of "as the" in the doc of entropy rate.

Block entropy documentation:
- block_entropy([0,0,1,1,1,1,0,0,0], k=2, local=True) -> should have parameter b=4 otherwise the results differ from what inside the pdf. 

*   Link in Conditional mutual information doc points to the wrong wikipage: https://en.wikipedia.org/wiki/Conditional_entropy

**Comment by dglmoore** [comment]
These have all been taken care of!
